### ISSUE TITLE
vertical-isp installation problem

### ISSUE THREAD

**Issue by romaque** [OCA/vertical-isp#20]
Hi,
I'm trying to install vertical-isp in my odoo 8 but it does not appear in the list of applications. what is the process to install vertical-isp in odoo 8

**Comment by joaoalf** [comment]
Hi @romaque ,

The vertical-isp modules have not been ported to odoo 8 yet.

**Comment by romaque** [comment]
Do these modules work in version 9 or 10?

**Comment by joaoalf** [comment]
@romaque So far they have not been ported to the new API so in the manifest file they are tagged as no installable. In short, no.

I will close the issue for now.
