### ISSUE TITLE
[ADD] connector_equipment_netsapiens

### ISSUE THREAD

**Issue by max3903** [OCA/vertical-isp#29]
Depends on:
* #27 
* agreement_serviceprofile

This module adds the fields to the equipment backend:
* Client ID
* Client Secret

# Technical Specifications

## backend.equipment

- [ ] Add a char field "Client ID" (client)
- [ ] Add a char field "Client Secret" (client_secret)
- [ ] Add the following demo data:
```
Name: Netsapiens Demo Server
Host:
Client ID:
Client Secret: 
Username: 
Password:
Active: True
```

**Comment by dreispt** [comment]
"Client ID" and "Client Secret" seem generic enough to be added directly to `connector_equipment`, and avoid this additional module.

**Comment by murtuzasaleh** [comment]
> "Client ID" and "Client Secret" seem generic enough to be added directly to `connector_equipment`, and avoid this additional module.

@dreispt @max3903 Ok, so I will create PR and add code on the connector_equipment module.

**Comment by dreispt** [comment]
OK - so this Issue will be implemented through a change to connector_equipment, rather than a new module. Thanks!
