### ISSUE TITLE
[ADD] connector_equipment_import_cdr

### ISSUE THREAD

**Issue by max3903** [OCA/vertical-isp#30]
Depends on:
* #29 

This module allows to import the CDR data from the Netsapiens backend as Odoo analytic lines.

# Technical Specifications

## product.template

- [ ] Add the following demo data:
```
Name: Call
Type: Service
UoM: Minutes
Can be sold: True
Can be purchased: True
Variants: 
  - Type: Domestic, International, Toll Free
```

## agreement.serviceprofile

- [ ] Add a char field "Domain" (domain)
- [ ] Add a date field "Last CDR Data Sync Date" (last_cdr_sync)
- [ ] ~~Display those fields if the type is "???"~~

## backend.equipment.netsapiens.product_line

- [ ] Add a backend.netsapiens.product_line object
- [ ] Add a many2one field "Product" (name) to product.product
- [ ] Add a char field "Pattern" (pattern) with help="The pattern is a regular expression that will applied on the phone number to detect a domestic call, an international call or a toll free call."
- [ ] Add an integer field "Sequence" (sequence).
- [ ] Add a many2one field "Backend" (backend_id) to backend.equipment
- [ ] Use the sequence field to sort the records
- [ ] Add the following demo data:
```
Sequence,Product,Pattern,Backend
10, Call(International),**,Netsapiens Demo Server
20, Call(Toll Free),**,Netsapiens Demo Server
30, Call(Domestic),**,Netsapiens Demo Server
```

## backend.equipment

- [ ] Add a one2many field "Products" (product_line_ids) to backend.equipment.netsapiens.product_line using the field Backend
- [ ] Add a selection field "Sync Schedule" (sync_schedule) with the option "All Service Profiles Every Day"
- [ ] Add a method import_cdr(self, serviceprofile_ids=None):
for each service profile with a domain, and an equipment related to this backend
* get the CDR data filtering them with the entries between the "Last CDR Data Sync Date" on the service profile and yesterday
* create the corresponding analytic entries using the fields mapping table above
* Set the "Last CDR Data Sync Date" to today on the service profile
- [ ] Add a button "Run Manually" to execute import_cdr
- [ ] Add a method cron_import_cdr(self)
For all backends,
* if "Sync Schedule" is "All Service Profiles Every Day"
  * run import_cdr
- [ ] Add a scheduled action to run cron_import_cdr everyday

**Comment by dreispt** [comment]
## agreement.serviceprofile

- I don't see the point for the Domain field.
- The last_cdr_sync date rather be on backend.equipment? If you have two equipements, these will be two separate imports.


## backend.equipment.netsapiens.product_line

- Name it instead `backend.equipment.product_line`, since this does not have to be Netsapiens CRD specific, could have other use cases.

**Comment by dreispt** [comment]
I edited the tech design with my suggestions.
I feel that the features are generic enough that they don't have to be tied specifically to Netsapiens equipments.

**Comment by kvedder-amplex** [comment]
Yeah that makes sense, as some may want to import CDR's into other systems.

**Comment by murtuzasaleh** [comment]
#43

**Comment by dreispt** [comment]
@murtuzasaleh, on `import_cdr(self, serviceprofile_ids=None)`:
It should consider the `serviceprofile_ids`recordset if give,.
If not consider all existing Service Profiles, with a `domain` set an an Equipment related to the this backend. 
You will need and outside loop on `self`, to handle one backend at a time.

Do your best approach at this, we can always fix/improve after.
