### ISSUE TITLE
[ADD] base_phone_rate

### ISSUE THREAD

**Issue by max3903** [OCA/vertical-isp#33]
This module allows you to store the International phone rate of your carrier.

# Usage

* Go to Contacts > Configuration > Localizations > Phone Rates
* Add Phone Rates by entering the name, country, state, dial prefix and rate

# Technical Specifications

## decimal.precision

- [ ] Add a record "Phone Rate" with 5 digits

## phone.rate

- [ ] Add a required char field "Name" (name)
- [ ] Add a required many2one field "Country" (country_id)
- [ ] Add a many2one field "State" (state_id)
- [ ] Add a required char field "Dial Prefix" (dial_prefix). Add a uniqueness constraint.
- [ ] Add a required float field "Rate" (rate)

**Comment by dreispt** [comment]
I'm not totally happy with the Menu path, but I'm not able to suggest a better one...
