### ISSUE TITLE
[ADD] base_phone_rate_bandwidth

### ISSUE THREAD

**Issue by max3903** [OCA/vertical-isp#34]
This module allows you to load and update the phone rates using the file provided by Bandwidth (https://www.bandwidth.com).

Bandwidth | Transformation | Odoo | Comments
-- | -- | -- | --
Destination / Country / Description | None | Name |  
Destination / Country / Description | Find the Odoo country with the string before " (" | Country |  
  |   | State | Empty
Dial Prefix | None | Dial Prefix | Value must be unique. Used to update the rate.
Rate | None | Rate |  

# Usage

* Go to Contacts > Configuration > Localizations > Phone Rates
* In the Action menu, click on "Import Bandwidth Rates"
* Select the file and click "Import"

New records will be created unless a dial prefix already exists. In this case, the rate is updated.

# Technical Specifications

## phone.rate

- [ ] Add a wizard to upload the spreadsheet provided by Bandwidth
- [ ] Add a server action to start the wizard
- [ ] Add a binary field "Upload File" to the wizard
- [ ] When clicking on "Import", create new records using the mapping above or update the rate based on the Dial Prefix

**Comment by dreispt** [comment]
"Bandwith" is not intended to be taken literally, and rather refers to a company/service,.
So I suggest:
- change module name to `base_phone_rate_import_bandwith` "Import Phone Rates from Bandwith.com"
- menu item > "Import Rates from Bandwidth.com"

**Comment by murtuzasaleh** [comment]
#44

**Comment by dreispt** [comment]
Implemented by #45
