### ISSUE TITLE
[ADD] product_isp

### ISSUE THREAD

**Issue by max3903** [OCA/vertical-isp#35]
This module allows you to define the international call services and use the phone rates.

# Usage

* Go to Sales > Catalog > Products
* Select or a create a product
* Select the type "Service"
* Check the box "International Call Service"

# Technical Specifications

## product.product

- [ ] Add a checkbox "International Call Service"
- [ ] Show the previous checkbox only if the type is service
- [ ] Add a smart button to show the phone rates and show it if International Call Service is true

**Comment by dreispt** [comment]
I think this module is not necessary.
"International call" products are configured in `backend.equipment.netsapiens.product_line` (#30)
